# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Escapdes in Dev
tagline:             'about technology, Japan and other things'
description:         'Some posts about being doing system architecture in Japan. Made by <a href="https://twitter.com/icchanosaur" target="_blank">@icchan</a>.'
url:                 http://icchan.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Ian Chen
  url:               http://bubblemix.net
  email:             blog@bubblemix.net

# Custom vars
version:             1.0.0
